apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: chart
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go-plugin/release.yaml@versionStream
          name: ""
          resources: {}
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}
        - name: next-version
          resources: {}
        - name: jx-variables
          resources: {}
        - name: release-binary
          resources: {}
        - name: build-and-push-image
          resources: {}
        - name: chart-docs
          resources: {}
        - image: gcr.io/jenkinsxio/jx-boot:3.0.773
          name: release-chart
          resources: {}
          script: |
            #!/usr/bin/env sh
            if [ -d "/workspace/source/charts/$REPO_NAME" ]; then source .jx/variables.sh
            cd /workspace/source/charts/$REPO_NAME
            make release; else echo no charts; fi
        - image: gcr.io/jenkinsxio/jx-boot:3.0.773
          name: set-github-action-version
          resources: {}
          script: |
            #!/usr/bin/env sh
            source .jx/variables.sh
            sed -i -e "s/jx-release-version:[0-9\.]*/jx-release-version:$VERSION/" action.yml
        - name: changelog
          resources: {}
        - name: upload-binaries
          resources: {}
        - name: promote-release
          resources: {}
        - image: gcr.io/jenkinsxio/jx-changelog:0.0.36
          name: promote-action
          resources: {}
          script: |
            #!/usr/bin/env sh
            source .jx/variables.sh

            git clone https://github.com/jenkins-x-plugins/$REPO_NAME update-action
            cd update-action
            sed -i -e "s|gcr.io/jenkinsxio/$REPO_NAME:.*|gcr.io/jenkinsxio/$REPO_NAME:$VERSION'|" action.yml

            git add * || true
            git commit -a -m "chore: upgrade image to $VERSION" --allow-empty
            git push
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
